# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
commands:
    # Install numpy and cython first to handle fatslim build dependencies
    - pip install numpy==1.23.5

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: biobb_mem/docs/source/conf.py

python:
  install:
    - requirements: biobb_mem/docs/requirements.txt
    - method: pip
      path: .